version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/db-data:/var/lib/postgresql/data
  api:
    image: node-api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env

